version: "3"
services:
  web:
    build: .
    image: akka-boot
    environment:
      environment: development
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
      - "444:444"

  loggly:
    image: sendgridlabs/loggly-docker
    environment:
      LOGGLY_AUTH_TOKEN: "FILL_ME_IN"
      LOGGLY_TAG: "akka-boot"