version: "3"
services:
  web:
    build: .
    image: wmfoody/akka-boot:latest
    environment:
      environment: development
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
      - "444:444"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]

  loggly:
    image: sendgridlabs/loggly-docker
    environment:
      LOGGLY_AUTH_TOKEN: "FILL_ME_IN"
      LOGGLY_TAG: "akka-boot"
    deploy:
      mode: global