version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.ivy2
            - ~/.sbt
          key: v1-dependencies-{{ checksum "build.sbt" }}

      # run tests!
      - run: cat /dev/null | sbt test:test

      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-reports/
            find . -type f -regex ".*/target/test-reports/.*xml" -exec cp {} ~/test-reports/ \;
          when: always

      - store-test-results:
          path: ~/test-reports/

      - store-artifacts:
          path: ~/test-reports/

  deploy:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    steps:
      - checkout

      - setup_remote_docker:
          docker_layer_caching: true

      - run: deployment/deploy_environment.sh

      - run: deployment/deploy_application.sh dev

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
#          filters:
#            branches:
#              only: master